db:
  image: mysql:5.7.20
  container_name: eventmanager-db
  volumes:
   - /var/lib/mysql
  ports:
   - "33061:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=eventmanager
   - MYSQL_DATABASE=eventmanager
   - MYSQL_USER=eventmanager
   - MYSQL_PASSWORD=eventmanager

redis:
  image: redis:3.2.11
  container_name: eventmanager-redis
  ports:
   - "63791:6379"
  environment:
   - ALLOW_EMPTY_PASSWORD=yes

phpfpm:
  build: ./php
  container_name: eventmanager-phpfpm
  links:
    - db:eventmanager-db
    - redis:eventmanager-redis
  ports:
   - "9090:9000"
   - "8081:8081"
  volumes:
   - ./http:/srv/http
  working_dir: /srv/http

server:
  image: nginx:1.13.8
  container_name: eventmanager-server
  links:
    - phpfpm:phpfpm
  ports:
   - "8082:8082"
   - "8080:80"
   - "4433:443"
  volumes:
   - ./http:/usr/share/nginx/html
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf

rediscommander:
  image: rediscommander/redis-commander:latest
  container_name: eventmanager-redis-commander
  links:
    - redis:eventmanager-redis
  ports:
    - 8380:8081
  environment:
    - REDIS_HOSTS=docker:eventmanager-redis:6379
